### PR TITLE
Smoke tests for cardinality estimators proposed by Google.

### PR DESCRIPTION
**Pull request by huangxichen1**
This pull request contains the smoke tests evaluation report for three cardinality estimators proposed by Google, including the exponential ADBF, log ADBF and Vector of Counts.

### CODE REVIEW

**Comment by my2457** [comment]
Seems run_evaluation breaks on this version. It's not a critical issue since it seems to be a trivial [code reference issue](https://github.com/world-federation-of-advertisers/cardinality_estimation_evaluation_framework/blob/huangxichen/smoke_test_report/src/evaluations/analyzer.py#L65), but can we add the base commit hash in readme of for each run? I'm assuming all the results will not involve code changes, so just the commit number of the code run before should be fine?

**Comment by huangxichen1** [comment]
> Seems run_evaluation breaks on this version. It's not a critical issue since it seems to be a trivial [code reference issue](https://github.com/world-federation-of-advertisers/cardinality_estimation_evaluation_framework/blob/huangxichen/smoke_test_report/src/evaluations/analyzer.py#L65), but can we add the base commit hash in readme of for each run? I'm assuming all the results will not involve code changes, so just the commit number of the code run before should be fine?

I added the commit hash number and link to the readme file. PTAL. Thanks!

**Comment by huangxichen1** [comment]
> lgtm
> one thing to confirm, so we run
> run_evaluation.py
> with the following and things are copy pasted, correct?
> --evaluation_config="smoke_test" --sketch_estimator_configs="vector_of_counts-4096-ln3-sequential" --sketch_estimator_configs="vector_of_counts-4096-infty-sequential" --sketch_estimator_configs="log_bloom_filter-1e5-ln3-first_moment_log" --sketch_estimator_configs="log_bloom_filter-1e5-infty-first_moment_log" --sketch_estimator_configs="exp_bloom_filter-1e5_10-ln3-first_moment_exp" --sketch_estimator_configs="exp_bloom_filter-1e5_10-infty-first_moment_exp" --num_runs=20

Right. We use num_runs=100 in this evaluation.

**Comment by my2457** [comment]
> > lgtm
> > one thing to confirm, so we run
> > run_evaluation.py
> > with the following and things are copy pasted, correct?
> > --evaluation_config="smoke_test" --sketch_estimator_configs="vector_of_counts-4096-ln3-sequential" --sketch_estimator_configs="vector_of_counts-4096-infty-sequential" --sketch_estimator_configs="log_bloom_filter-1e5-ln3-first_moment_log" --sketch_estimator_configs="log_bloom_filter-1e5-infty-first_moment_log" --sketch_estimator_configs="exp_bloom_filter-1e5_10-ln3-first_moment_exp" --sketch_estimator_configs="exp_bloom_filter-1e5_10-infty-first_moment_exp" --num_runs=20
> 
> Right. We use num_runs=100 in this evaluation.

looks good to us on fb side, so feel free to merge

**Pull request merged**
